In [ ]:
import pandas as pd
import numpy as np



1.   Pagar infomação dos dados usando, como o tipo de cada coluna as colunas.
2.   Agora vamos ter que ver quais dados poderão ser utilizadas


3.   Depois de ver quais dados são importantes tá na hora de excluir as colunas
4.   Achando valores Outliers
---

In [ ]:
dados = pd.read_csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/latest/owid-covid-latest.csv")
dados

,iso_code,continent,location,last_updated_date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2023-07-19,223846.0,0.0,22.286,7932.0,0.0,0.000,...,NaN,37.746,0.500,64.83,0.511,4.112877e+07,NaN,NaN,NaN,NaN
1,OWID_AFR,NaN,Africa,2023-07-19,13102443.0,0.0,134.143,258991.0,0.0,1.286,...,NaN,NaN,NaN,NaN,NaN,1.426737e+09,NaN,NaN,NaN,NaN
2,ALB,Europe,Albania,2023-07-19,334090.0,0.0,0.000,3604.0,0.0,0.000,...,51.200,NaN,2.890,78.57,0.795,2.842318e+06,NaN,NaN,NaN,NaN
3,DZA,Africa,Algeria,2023-07-19,271852.0,0.0,0.000,6881.0,0.0,0.000,...,30.400,83.741,1.900,76.88,0.748,4.490323e+07,NaN,NaN,NaN,NaN
4,ASM,Oceania,American Samoa,2023-07-19,8332.0,0.0,0.000,34.0,0.0,0.000,...,NaN,NaN,NaN,73.74,NaN,4.429500e+04,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,WLF,Oceania,Wallis and Futuna,2023-07-19,3550.0,0.0,0.000,8.0,0.0,0.000,...,NaN,NaN,NaN,79.94,NaN,1.159600e+04,NaN,NaN,NaN,NaN
247,OWID_WRL,NaN,World,2023-07-20,768237024.0,0.0,33908.857,6951664.0,0.0,70.143,...,34.635,60.130,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN
248,YEM,Asia,Yemen,2023-07-19,11945.0,0.0,0.000,2159.0,0.0,0.000,...,29.200,49.542,0.700,66.12,0.470,3.369661e+07,NaN,NaN,NaN,NaN
249,ZMB,Africa,Zambia,2023-07-19,347022.0,0.0,0.000,4062.0,0.0,0.000,...,24.700,13.938,2.000,63.89,0.584,2.001767e+07,NaN,NaN,NaN,NaN
250,ZWE,Africa,Zimbabwe,2023-07-19,265666.0,0.0,8.857,5711.0,0.0,0.286,...,30.700,36.791,1.700,61.49,0.571,1.632054e+07,NaN,NaN,NaN,NaN

In [ ]:
print('Tamanho do DataFrame')
display(dados.shape)
display(dados.size)

Tamanho do DataFrame

(251, 67)

16817

In [ ]:
dados.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,2.440000e+02,246.000000,246.000000,2.380000e+02,246.000000,246.000000,244.000000,246.000000,246.000000,238.000000,...,145.000000,96.000000,173.000000,231.000000,189.000000,2.510000e+02,2.000000,2.000000,2.00000,2.000000
mean,1.334193e+07,948.894309,553.943683,1.220374e+05,1.670732,1.158545,201580.609377,22.860549,4.177524,1294.028731,...,32.909897,50.788844,3.097012,73.641818,0.721302,1.290143e+08,33988.050500,9.055000,-1.83500,1983.849500
std,6.520152e+07,13080.955365,3922.467116,5.728609e+05,12.563363,6.170012,197132.343338,256.903169,36.887032,1294.265528,...,13.621757,32.124848,2.555777,7.382418,0.148876,6.632137e+08,42028.941442,9.751003,10.52882,1784.183851
min,4.000000e+00,0.000000,0.000000,1.000000e+00,0.000000,0.000000,354.487000,0.000000,0.000000,1.164000,...,7.700000,1.188000,0.100000,53.280000,0.394000,4.700000e+01,4269.101000,2.160000,-9.28000,722.241000
25%,2.784400e+04,0.000000,0.000000,2.397500e+02,0.000000,0.000000,24322.639250,0.000000,0.000000,182.409250,...,22.600000,20.482000,1.300000,69.545000,0.602000,4.864000e+05,19128.575750,5.607500,-5.55750,1353.045250
50%,2.318855e+05,0.000000,0.000000,2.670000e+03,0.000000,0.000000,136256.488000,0.000000,0.000000,945.213500,...,33.100000,49.690500,2.500000,75.050000,0.740000,5.882259e+06,33988.050500,9.055000,-1.83500,1983.849500
75%,1.722332e+06,0.000000,0.571000,2.015450e+04,0.000000,0.000000,333747.038250,0.000000,0.032750,2054.604000,...,41.300000,82.686750,4.200000,79.285000,0.828000,2.895671e+07,48847.525250,12.502500,1.88750,2614.653750
max,7.682370e+08,204911.000000,33908.857000,6.951664e+06,161.000000,70.143000,737554.506000,3954.604000,564.943000,6496.496000,...,78.100000,100.000000,13.800000,86.750000,0.957000,7.975105e+09,63707.000000,15.950000,5.61000,3245.458000

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    251 non-null    object
 1   continent                                   239 non-null    object
 2   location                                    251 non-null    object
 3   last_updated_date                           251 non-null    object
 4   total_cases                                 244 non-null    float64
 5   new_cases                                   246 non-null    float64
 6   new_cases_smoothed                          246 non-null    float64
 7   total_deaths                                238 non-null    float64
 8   new_deaths                                  246 non-null    float64
 9   new_deaths_smoothed                         246 non-null    float64
 10  total_cases_per_million                     244 non-null    float64
 11  new_cases_per_million                       246 non-null    float64
 12  new_cases_smoothed_per_million              246 non-null    float64
 13  total_deaths_per_million                    238 non-null    float64
 14  new_deaths_per_million                      246 non-null    float64
 15  new_deaths_smoothed_per_million             246 non-null    float64
 16  reproduction_rate                           0 non-null      float64
 17  icu_patients                                17 non-null     float64
 18  icu_patients_per_million                    17 non-null     float64
 19  hosp_patients                               16 non-null     float64
 20  hosp_patients_per_million                   16 non-null     float64
 21  weekly_icu_admissions                       10 non-null     float64
 22  weekly_icu_admissions_per_million           10 non-null     float64
 23  weekly_hosp_admissions                      13 non-null     float64
 24  weekly_hosp_admissions_per_million          13 non-null     float64
 25  total_tests                                 0 non-null      float64
 26  new_tests                                   0 non-null      float64
 27  total_tests_per_thousand                    0 non-null      float64
 28  new_tests_per_thousand                      0 non-null      float64
 29  new_tests_smoothed                          0 non-null      float64
 30  new_tests_smoothed_per_thousand             0 non-null      float64
 31  positive_rate                               0 non-null      float64
 32  tests_per_case                              0 non-null      float64
 33  tests_units                                 0 non-null      float64
 34  total_vaccinations                          37 non-null     float64
 35  people_vaccinated                           37 non-null     float64
 36  people_fully_vaccinated                     38 non-null     float64
 37  total_boosters                              32 non-null     float64
 38  new_vaccinations                            29 non-null     float64
 39  new_vaccinations_smoothed                   37 non-null     float64
 40  total_vaccinations_per_hundred              37 non-null     float64
 41  people_vaccinated_per_hundred               37 non-null     float64
 42  people_fully_vaccinated_per_hundred         38 non-null     float64
 43  total_boosters_per_hundred                  32 non-null     float64
 44  new_vaccinations_smoothed_per_million       37 non-null     float64
 45  new_people_vaccinated_smoothed              37 non-null     float64
 46  new_people_vaccinated_smoothed_per_hundred  37 non-null     float64
 47  stringency_index                            0 non-null      float64
 48  population_density                          213 non-null    float64
 49  median_age                                  198 non-null    float64
 50  aged_65_older                               191 non-null    float64
 51  aged_70_older                               196 non-null    float64
 52  gdp_per_capita                              194 non-null    float64
 53  extreme_poverty                             126 non-null    float64
 54  cardiovasc_death_rate                       196 non-null    float64
 55  diabetes_prevalence                         205 non-null    float64
 56  female_smokers                              147 non-null    float64
 57  male_smokers                                145 non-null    float64
 58  handwashing_facilities                      96 non-null     float64
 59  hospital_beds_per_thousand                  173 non-null    float64
 60  life_expectancy                             231 non-null    float64
 61  human_development_index                     189 non-null    float64
 62  population                                  251 non-null    float64
 63  excess_mortality_cumulative_absolute        2 non-null      float64
 64  excess_mortality_cumulative                 2 non-null      float64
 65  excess_mortality                            2 non-null      float64
 66  excess_mortality_cumulative_per_million     2 non-null      float64
dtypes: float64(63), object(4)
memory usage: 131.5+ KB

In [ ]:
dados.columns

Index(['iso_code', 'continent', 'location', 'last_updated_date', 'total_cases',
       'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population_density', 'median_age', 'aged_65_older', 'aged_70_older',
       'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'population',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
       'excess_mortality', 'excess_mortality_cumulative_per_million'],
      dtype='object')

In [ ]:
dados.isnull()

,iso_code,continent,location,last_updated_date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,True,True,True
1,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,False,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,True,False,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,True,False,True,True,True,True
247,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True
248,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True
249,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True
250,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True

In [ ]:
dados.isnull().sum()

iso_code                                     0
continent                                   12
location                                     0
last_updated_date                            0
total_cases                                  7
                                          ...
population                                   0
excess_mortality_cumulative_absolute       249
excess_mortality_cumulative                249
excess_mortality                           249
excess_mortality_cumulative_per_million    249
Length: 67, dtype: int64

In [ ]:
dados.drop_duplicates(inplace=True)
dados

,iso_code,continent,location,last_updated_date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2023-07-19,223846.0,0.0,22.286,7932.0,0.0,0.000,...,NaN,37.746,0.500,64.83,0.511,4.112877e+07,NaN,NaN,NaN,NaN
1,OWID_AFR,NaN,Africa,2023-07-19,13102443.0,0.0,134.143,258991.0,0.0,1.286,...,NaN,NaN,NaN,NaN,NaN,1.426737e+09,NaN,NaN,NaN,NaN
2,ALB,Europe,Albania,2023-07-19,334090.0,0.0,0.000,3604.0,0.0,0.000,...,51.200,NaN,2.890,78.57,0.795,2.842318e+06,NaN,NaN,NaN,NaN
3,DZA,Africa,Algeria,2023-07-19,271852.0,0.0,0.000,6881.0,0.0,0.000,...,30.400,83.741,1.900,76.88,0.748,4.490323e+07,NaN,NaN,NaN,NaN
4,ASM,Oceania,American Samoa,2023-07-19,8332.0,0.0,0.000,34.0,0.0,0.000,...,NaN,NaN,NaN,73.74,NaN,4.429500e+04,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,WLF,Oceania,Wallis and Futuna,2023-07-19,3550.0,0.0,0.000,8.0,0.0,0.000,...,NaN,NaN,NaN,79.94,NaN,1.159600e+04,NaN,NaN,NaN,NaN
247,OWID_WRL,NaN,World,2023-07-20,768237024.0,0.0,33908.857,6951664.0,0.0,70.143,...,34.635,60.130,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN
248,YEM,Asia,Yemen,2023-07-19,11945.0,0.0,0.000,2159.0,0.0,0.000,...,29.200,49.542,0.700,66.12,0.470,3.369661e+07,NaN,NaN,NaN,NaN
249,ZMB,Africa,Zambia,2023-07-19,347022.0,0.0,0.000,4062.0,0.0,0.000,...,24.700,13.938,2.000,63.89,0.584,2.001767e+07,NaN,NaN,NaN,NaN
250,ZWE,Africa,Zimbabwe,2023-07-19,265666.0,0.0,8.857,5711.0,0.0,0.286,...,30.700,36.791,1.700,61.49,0.571,1.632054e+07,NaN,NaN,NaN,NaN

In [ ]:
dados.isnull().sum()

iso_code                                     0
continent                                   12
location                                     0
last_updated_date                            0
total_cases                                  7
                                          ...
population                                   0
excess_mortality_cumulative_absolute       249
excess_mortality_cumulative                249
excess_mortality                           249
excess_mortality_cumulative_per_million    249
Length: 67, dtype: int64

In [ ]:
class robo:
  def __init__(self,dados):
    self.dados = dados
    self.dados = pd.read_csv(dados)
  def removendo_dados_nulos(self):
    #limpando dados nulos
    self.v_f = self.dados.isnull().sum() > 200
    self.v_f = v_f.loc[v_f == True]
    for self.c in self.v_f.index:
      df.drop(self.c,inplace=True,axis=1)
  def substituindo_media(self):
    # Pegando a media desse valores e colocando no lugar dos valores nulos
    pass