In [1]:
import pandas as pd
import numpy as np



1.   Pagar infomação dos dados usando, como o tipo de cada coluna as colunas.
2.   Agora vamos ter que ver quais dados poderão ser utilizadas


3.   Depois de ver quais dados são importantes tá na hora de excluir as colunas
4.   Achando valores Outliers
---

In [2]:
dados = pd.read_csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/latest/owid-covid-latest.csv")
dados

,iso_code,continent,location,last_updated_date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2023-07-26,224057.0,0.0,18.286,7933.0,0.0,0.143,...,NaN,37.746,0.500,64.83,0.511,4.112877e+07,NaN,NaN,NaN,NaN
1,OWID_AFR,NaN,Africa,2023-07-26,13105032.0,0.0,10.286,258999.0,0.0,0.000,...,NaN,NaN,NaN,NaN,NaN,1.426737e+09,NaN,NaN,NaN,NaN
2,ALB,Europe,Albania,2023-07-26,334090.0,0.0,0.000,3604.0,0.0,0.000,...,51.200,NaN,2.890,78.57,0.795,2.842318e+06,NaN,NaN,NaN,NaN
3,DZA,Africa,Algeria,2023-07-26,271852.0,0.0,0.000,6881.0,0.0,0.000,...,30.400,83.741,1.900,76.88,0.748,4.490323e+07,NaN,NaN,NaN,NaN
4,ASM,Oceania,American Samoa,2023-07-26,8332.0,0.0,0.000,34.0,0.0,0.000,...,NaN,NaN,NaN,73.74,NaN,4.429500e+04,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,WLF,Oceania,Wallis and Futuna,2023-07-26,3550.0,0.0,0.000,8.0,0.0,0.000,...,NaN,NaN,NaN,79.94,NaN,1.159600e+04,NaN,NaN,NaN,NaN
245,OWID_WRL,NaN,World,2023-07-31,768559963.0,0.0,41415.857,6952509.0,0.0,53.714,...,34.635,60.130,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN
246,YEM,Asia,Yemen,2023-07-26,11945.0,0.0,0.000,2159.0,0.0,0.000,...,29.200,49.542,0.700,66.12,0.470,3.369661e+07,NaN,NaN,NaN,NaN
247,ZMB,Africa,Zambia,2023-07-26,349287.0,0.0,0.000,4069.0,0.0,0.000,...,24.700,13.938,2.000,63.89,0.584,2.001767e+07,NaN,NaN,NaN,NaN
248,ZWE,Africa,Zimbabwe,2023-07-26,265666.0,0.0,0.000,5711.0,0.0,0.000,...,30.700,36.791,1.700,61.49,0.571,1.632054e+07,NaN,NaN,NaN,NaN

In [3]:
print('Tamanho do DataFrame')
display(dados.shape)
display(dados.size)

Tamanho do DataFrame

(249, 67)

16683

In [4]:
dados.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,2.440000e+02,246.000000,246.000000,2.380000e+02,246.000000,246.000000,244.000000,246.000000,246.000000,238.000000,...,145.000000,96.000000,173.000000,230.000000,189.000000,2.490000e+02,3.000000,3.000000,3.000000,3.00000
mean,1.334725e+07,1166.268293,677.139967,1.220521e+05,1.284553,0.887350,201697.077881,29.342126,4.802557,1294.444782,...,32.909897,50.788844,3.097012,73.612174,0.721302,1.299419e+08,24107.066000,8.540000,-3.306667,2421.06700
std,6.523043e+07,16260.334243,4835.138726,5.729294e+05,11.457478,4.929356,197157.247099,320.192790,45.816058,1294.415094,...,13.621757,32.124848,2.555777,7.384727,0.148876,6.658005e+08,34243.280642,6.821166,4.467061,1463.65124
min,4.000000e+00,0.000000,0.000000,1.000000e+00,0.000000,0.000000,354.487000,0.000000,0.000000,1.164000,...,7.700000,1.188000,0.100000,53.280000,0.394000,4.700000e+01,4322.101000,2.160000,-7.850000,731.20700
25%,2.784400e+04,0.000000,0.000000,2.397500e+02,0.000000,0.000000,24322.639250,0.000000,0.000000,182.409250,...,22.600000,20.482000,1.300000,69.522500,0.602000,4.490020e+05,4336.700500,4.945000,-5.500000,1986.82450
50%,2.318855e+05,0.000000,0.000000,2.670000e+03,0.000000,0.000000,136256.488000,0.000000,0.000000,945.213500,...,33.100000,49.690500,2.500000,75.025000,0.740000,5.882259e+06,4351.300000,7.730000,-3.150000,3242.44200
75%,1.722498e+06,0.000000,0.000000,2.015825e+04,0.000000,0.000000,334659.993500,0.000000,0.000000,2054.604000,...,41.300000,82.686750,4.200000,79.160000,0.828000,2.961172e+07,33999.548500,11.730000,-1.035000,3265.99700
max,7.685600e+08,254841.000000,41415.857000,6.952509e+06,168.000000,53.714000,737554.506000,4918.210000,702.601000,6498.199000,...,78.100000,100.000000,13.800000,86.750000,0.957000,7.975105e+09,63647.797000,15.730000,1.080000,3289.55200

In [5]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    249 non-null    object
 1   continent                                   237 non-null    object
 2   location                                    249 non-null    object
 3   last_updated_date                           249 non-null    object
 4   total_cases                                 244 non-null    float64
 5   new_cases                                   246 non-null    float64
 6   new_cases_smoothed                          246 non-null    float64
 7   total_deaths                                238 non-null    float64
 8   new_deaths                                  246 non-null    float64
 9   new_deaths_smoothed                         246 non-null    float64
 10  total_cases_per_million                     244 non-null    float64
 11  new_cases_per_million                       246 non-null    float64
 12  new_cases_smoothed_per_million              246 non-null    float64
 13  total_deaths_per_million                    238 non-null    float64
 14  new_deaths_per_million                      246 non-null    float64
 15  new_deaths_smoothed_per_million             246 non-null    float64
 16  reproduction_rate                           0 non-null      float64
 17  icu_patients                                15 non-null     float64
 18  icu_patients_per_million                    15 non-null     float64
 19  hosp_patients                               14 non-null     float64
 20  hosp_patients_per_million                   14 non-null     float64
 21  weekly_icu_admissions                       10 non-null     float64
 22  weekly_icu_admissions_per_million           10 non-null     float64
 23  weekly_hosp_admissions                      12 non-null     float64
 24  weekly_hosp_admissions_per_million          12 non-null     float64
 25  total_tests                                 0 non-null      float64
 26  new_tests                                   0 non-null      float64
 27  total_tests_per_thousand                    0 non-null      float64
 28  new_tests_per_thousand                      0 non-null      float64
 29  new_tests_smoothed                          0 non-null      float64
 30  new_tests_smoothed_per_thousand             0 non-null      float64
 31  positive_rate                               0 non-null      float64
 32  tests_per_case                              0 non-null      float64
 33  tests_units                                 0 non-null      float64
 34  total_vaccinations                          40 non-null     float64
 35  people_vaccinated                           39 non-null     float64
 36  people_fully_vaccinated                     40 non-null     float64
 37  total_boosters                              36 non-null     float64
 38  new_vaccinations                            26 non-null     float64
 39  new_vaccinations_smoothed                   40 non-null     float64
 40  total_vaccinations_per_hundred              40 non-null     float64
 41  people_vaccinated_per_hundred               39 non-null     float64
 42  people_fully_vaccinated_per_hundred         40 non-null     float64
 43  total_boosters_per_hundred                  36 non-null     float64
 44  new_vaccinations_smoothed_per_million       40 non-null     float64
 45  new_people_vaccinated_smoothed              39 non-null     float64
 46  new_people_vaccinated_smoothed_per_hundred  39 non-null     float64
 47  stringency_index                            0 non-null      float64
 48  population_density                          213 non-null    float64
 49  median_age                                  197 non-null    float64
 50  aged_65_older                               191 non-null    float64
 51  aged_70_older                               195 non-null    float64
 52  gdp_per_capita                              194 non-null    float64
 53  extreme_poverty                             126 non-null    float64
 54  cardiovasc_death_rate                       195 non-null    float64
 55  diabetes_prevalence                         205 non-null    float64
 56  female_smokers                              147 non-null    float64
 57  male_smokers                                145 non-null    float64
 58  handwashing_facilities                      96 non-null     float64
 59  hospital_beds_per_thousand                  173 non-null    float64
 60  life_expectancy                             230 non-null    float64
 61  human_development_index                     189 non-null    float64
 62  population                                  249 non-null    float64
 63  excess_mortality_cumulative_absolute        3 non-null      float64
 64  excess_mortality_cumulative                 3 non-null      float64
 65  excess_mortality                            3 non-null      float64
 66  excess_mortality_cumulative_per_million     3 non-null      float64
dtypes: float64(63), object(4)
memory usage: 130.5+ KB

In [6]:
dados.columns

Index(['iso_code', 'continent', 'location', 'last_updated_date', 'total_cases',
       'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population_density', 'median_age', 'aged_65_older', 'aged_70_older',
       'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'population',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
       'excess_mortality', 'excess_mortality_cumulative_per_million'],
      dtype='object')

In [7]:
dados.isnull()

,iso_code,continent,location,last_updated_date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,True,True,True
1,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,False,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,True,False,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,True,False,True,True,True,True
245,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True
246,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True
247,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True
248,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True

In [8]:
dados.isnull().sum()

iso_code                                     0
continent                                   12
location                                     0
last_updated_date                            0
total_cases                                  5
                                          ...
population                                   0
excess_mortality_cumulative_absolute       246
excess_mortality_cumulative                246
excess_mortality                           246
excess_mortality_cumulative_per_million    246
Length: 67, dtype: int64

In [9]:
dados.drop_duplicates(inplace=True)
dados

,iso_code,continent,location,last_updated_date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2023-07-26,224057.0,0.0,18.286,7933.0,0.0,0.143,...,NaN,37.746,0.500,64.83,0.511,4.112877e+07,NaN,NaN,NaN,NaN
1,OWID_AFR,NaN,Africa,2023-07-26,13105032.0,0.0,10.286,258999.0,0.0,0.000,...,NaN,NaN,NaN,NaN,NaN,1.426737e+09,NaN,NaN,NaN,NaN
2,ALB,Europe,Albania,2023-07-26,334090.0,0.0,0.000,3604.0,0.0,0.000,...,51.200,NaN,2.890,78.57,0.795,2.842318e+06,NaN,NaN,NaN,NaN
3,DZA,Africa,Algeria,2023-07-26,271852.0,0.0,0.000,6881.0,0.0,0.000,...,30.400,83.741,1.900,76.88,0.748,4.490323e+07,NaN,NaN,NaN,NaN
4,ASM,Oceania,American Samoa,2023-07-26,8332.0,0.0,0.000,34.0,0.0,0.000,...,NaN,NaN,NaN,73.74,NaN,4.429500e+04,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,WLF,Oceania,Wallis and Futuna,2023-07-26,3550.0,0.0,0.000,8.0,0.0,0.000,...,NaN,NaN,NaN,79.94,NaN,1.159600e+04,NaN,NaN,NaN,NaN
245,OWID_WRL,NaN,World,2023-07-31,768559963.0,0.0,41415.857,6952509.0,0.0,53.714,...,34.635,60.130,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN
246,YEM,Asia,Yemen,2023-07-26,11945.0,0.0,0.000,2159.0,0.0,0.000,...,29.200,49.542,0.700,66.12,0.470,3.369661e+07,NaN,NaN,NaN,NaN
247,ZMB,Africa,Zambia,2023-07-26,349287.0,0.0,0.000,4069.0,0.0,0.000,...,24.700,13.938,2.000,63.89,0.584,2.001767e+07,NaN,NaN,NaN,NaN
248,ZWE,Africa,Zimbabwe,2023-07-26,265666.0,0.0,0.000,5711.0,0.0,0.000,...,30.700,36.791,1.700,61.49,0.571,1.632054e+07,NaN,NaN,NaN,NaN

In [10]:
dados.isnull().sum()

iso_code                                     0
continent                                   12
location                                     0
last_updated_date                            0
total_cases                                  5
                                          ...
population                                   0
excess_mortality_cumulative_absolute       246
excess_mortality_cumulative                246
excess_mortality                           246
excess_mortality_cumulative_per_million    246
Length: 67, dtype: int64

In [12]:
# Excluindo dados nulos
v_f = dados.isnull().sum() > 200
v_f = v_f.loc[v_f == True]
for c in v_f.index:
  dados.drop(c,inplace=True,axis=1)

In [16]:
dados['continent'].fillna('País não encontrado',inplace=True)
dados.isnull().sum()

iso_code                             0
continent                            0
location                             0
last_updated_date                    0
total_cases                          5
new_cases                            3
new_cases_smoothed                   3
total_deaths                        11
new_deaths                           3
new_deaths_smoothed                  3
total_cases_per_million              5
new_cases_per_million                3
new_cases_smoothed_per_million       3
total_deaths_per_million            11
new_deaths_per_million               3
new_deaths_smoothed_per_million      3
population_density                  36
median_age                          52
aged_65_older                       58
aged_70_older                       54
gdp_per_capita                      55
extreme_poverty                    123
cardiovasc_death_rate               54
diabetes_prevalence                 44
female_smokers                     102
male_smokers                       104
handwashing_facilities             153
hospital_beds_per_thousand          76
life_expectancy                     19
human_development_index             60
population                           0
dtype: int64

In [18]:
# Pegando a media desse valores e colocando no lugar dos valores nulos
media_median = dados.isnull().sum() > 0
media_median = media_median.loc[media_median == True]
for j in media_median.index:
  media = dados[j].mean()
  mediana = dados[j].median()
  # Aplicando a media nos dados ausentes
  teste = dados[j].fillna(media,inplace=True) #Talvez não estaja funcionando